/**
 * Business Name Generator - Isolated Utilities
 * Copy, download, and localStorage helpers (independent of shared utils)
 */

export function downloadAsFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    const textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand("copy");
    document.body.removeChild(textarea);
    return success;
  }
}

export function saveTolocalStorage(key: string, value: string): void {
  try {
    localStorage.setItem(key, value);
  } catch (error) {
    console.error("localStorage save failed:", error);
  }
}

export function loadFromlocalStorage(key: string): string | null {
  try {
    return localStorage.getItem(key);
  } catch (error) {
    console.error("localStorage load failed:", error);
    return null;
  }
}

/**
 * Format generated names for export
 */
export function formatNamesForExport(
  names: any[],
  keywords: string[],
  style: string,
  industry: string
): string {
  const header = `BUSINESS NAME GENERATOR RESULTS
Generated on: ${new Date().toLocaleString()}

Keywords: ${keywords.join(", ")}
Style: ${style}
Industry: ${industry}

Generated Names:
========================\n`;

  const nameList = names
    .map((name, idx) => {
      return `${idx + 1}. ${name.name}
   Explanation: ${name.explanation}
   Availability: ${name.availability || "unknown"}
   Tags: ${(name.tags || []).join(", ")}\n`;
    })
    .join("\n");

  const footer = `\n========================
Generated by topaitoolrank.com Business Name Generator`;

  return header + nameList + footer;
}

/**
 * Format names as CSV
 */
export function formatNamesAsCSV(names: any[]): string {
  if (!names || names.length === 0) {
    return "";
  }

  // Header
  const header = ["Name", "Explanation", "Availability", "Tags"].join(",");

  // Rows
  const rows = names
    .map(name => {
      const explanation = (name.explanation || "").replace(/"/g, '""');
      const tags = ((name.tags || []) as string[]).join(";").replace(/"/g, '""');
      return [
        `"${name.name || ""}"`,
        `"${explanation}"`,
        `"${name.availability || ""}"`,
        `"${tags}"`,
      ].join(",");
    })
    .join("\n");

  return header + "\n" + rows;
}

/**
 * Validate domain-like name
 */
export function isValidDomainName(name: string): boolean {
  // Simple validation - must be alphanumeric with hyphens only
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/i.test(name);
}

/**
 * Count syllables in a word (rough estimate)
 */
export function estimateSyllables(word: string): number {
  const vowels = (word.match(/[aeiou]/gi) || []).length;
  return Math.max(1, vowels);
}

/**
 * Calculate memorability score (0-100)
 */
export function calculateMemorabilityScore(name: string): number {
  let score = 50;

  // Shorter names are more memorable
  if (name.length < 5) score += 15;
  else if (name.length > 15) score -= 15;

  // Alliteration is memorable
  if (/^([a-z])\w*\1/i.test(name)) score += 10;

  // Unique patterns are memorable
  if (/[A-Z]/.test(name)) score += 5;
  if (/[0-9]/.test(name)) score += 3;

  // Too many vowels or consonants is less memorable
  const vowels = (name.match(/[aeiou]/gi) || []).length;
  const consonants = (name.match(/[bcdfghjklmnpqrstvwxyz]/gi) || []).length;
  const ratio = vowels / (vowels + consonants);
  if (ratio > 0.6 || ratio < 0.2) score -= 10;

  return Math.max(0, Math.min(100, score));
}
