"use client";

export const dynamicParams = false;


/**
 * Email Subject Line Tester - Main Page
 * Score and optimize email subject lines for better open rates
 */

import { useState, useEffect, useMemo } from "react";
import styles from "./styles.css";
import { scoreSubjectLine, getSubjectLineStatistics } from "./lib/subject-scorer";
import { copyToClipboard, downloadAsFile, saveTolocalStorage, loadFromlocalStorage } from "./lib/utils";

const LOCALSTORAGE_KEY = "est-subject";

export default function EmailSubjectTesterPage() {
  const [subjectLine, setSubjectLine] = useState("");
  const [copyMessage, setCopyMessage] = useState("");

  // Load from localStorage on mount
  useEffect(() => {
    const saved = loadFromlocalStorage(LOCALSTORAGE_KEY);
    if (saved) setSubjectLine(saved);
  }, []);

  // Save to localStorage on change
  useEffect(() => {
    saveTolocalStorage(LOCALSTORAGE_KEY, subjectLine);
  }, [subjectLine]);

  const handleCopyScore = async () => {
    const scoreText = `Subject Line: "${subjectLine}"
Score: ${score.overallScore}/100 (${getScoreTier(score.overallScore)})
Open Rate: ${score.estimatedOpenRate}
Length: ${stats.characterCount} characters
Words: ${stats.wordCount}`;
    const success = await copyToClipboard(scoreText);
    if (success) {
      setCopyMessage("✓ Score copied!");
      setTimeout(() => setCopyMessage(""), 2000);
    }
  };

  const handleDownloadReport = () => {
    const report = `Email Subject Line Analysis
============================
Subject: "${subjectLine}"
Analysis Date: ${new Date().toLocaleDateString()}

OVERALL SCORE: ${score.overallScore}/100 (${getScoreTier(score.overallScore)})
Estimated Open Rate: ${score.estimatedOpenRate === "high" ? "🟢 High" : score.estimatedOpenRate === "medium" ? "🟡 Medium" : "🔴 Low"}

DIMENSION BREAKDOWN
Length: ${score.length.score}% - ${score.length.message}
Urgency: ${score.urgency.score}% - ${score.urgency.message}
Personalization: ${score.personalization.score}% - ${score.personalization.message}
Curiosity: ${score.curiosity.score}% - ${score.curiosity.message}
Power Words: ${score.powerWords.score}% - ${score.powerWords.message}
Formatting: ${score.specialCharacters.score}% - ${score.specialCharacters.message}

STATISTICS
Characters: ${stats.characterCount}
Words: ${stats.wordCount}
Numbers: ${stats.numbersCount}
Emoji: ${stats.hasEmoji ? "Yes" : "No"}

RECOMMENDATIONS
${score.suggestions.map((s, i) => `${i + 1}. ${s}`).join("\n")}

Generated by topaitoolrank.com Email Subject Line Tester`;

    downloadAsFile(report, `subject-line-report-${Date.now()}.txt`);
  };

  // Score and statistics
  const score = useMemo(() => scoreSubjectLine(subjectLine), [subjectLine]);
  const stats = useMemo(() => getSubjectLineStatistics(subjectLine), [subjectLine]);

  const getScoreColor = (scoreValue: number): string => {
    if (scoreValue >= 80) return "#10b981"; // green
    if (scoreValue >= 60) return "#f59e0b"; // amber
    return "#ef4444"; // red
  };

  const getScoreTier = (scoreValue: number): string => {
    if (scoreValue >= 90) return "Excellent";
    if (scoreValue >= 80) return "Good";
    if (scoreValue >= 70) return "Fair";
    if (scoreValue >= 60) return "Needs Work";
    return "Poor";
  };

  // This helper is used in the template and in handleDownloadReport
  const getScoreTierHelper = (scoreValue: number): string => getScoreTier(scoreValue);

  // @ts-ignore CSS Module types
  return (
    <div className={styles["email-subject-tester"]}>
      <header className={styles["email-subject-tester__header"]}>
        <h1>Email Subject Line Tester</h1>
        <p>Score and optimize your subject lines for better open rates</p>
      </header>

      <main className={styles["email-subject-tester__main"]}>
        {/* Input section */}
        <section className={styles["email-subject-tester__input-section"]}>
          <div className={styles["email-subject-tester__field"]}>
            <label className={styles["email-subject-tester__label"]}>
              Paste Your Subject Line
            </label>
            <input
              type="text"
              className={styles["email-subject-tester__input"]}
              value={subjectLine}
              onChange={(e) => setSubjectLine(e.target.value)}
              placeholder="e.g., Your exclusive 50% discount expires today..."
              maxLength={100}
            />
            <div className={styles["email-subject-tester__counter"]}>
              {subjectLine.length}/100 characters
            </div>
          </div>
        </section>

        {subjectLine && (
          <>
            {/* Overall Score */}
            <section className={styles["email-subject-tester__score-section"]}>
              <div className={styles["email-subject-tester__overall-score"]}>
                <div
                  className={styles["email-subject-tester__score-circle"]}
                  style={{ borderColor: getScoreColor(score.overallScore) }}
                >
                  <span className={styles["email-subject-tester__score-value"]}>
                    {score.overallScore}
                  </span>
                </div>
                <div className={styles["email-subject-tester__score-info"]}>
                  <h3 className={styles["email-subject-tester__score-tier"]}>
                    {getScoreTier(score.overallScore)}
                  </h3>
                  <p className={styles["email-subject-tester__open-rate"]}>
                    Estimated Open Rate:{" "}
                    <strong>{score.estimatedOpenRate === "high" ? "🟢 High" : score.estimatedOpenRate === "medium" ? "🟡 Medium" : "🔴 Low"}</strong>
                  </p>
                </div>
              </div>
            </section>

            {/* Dimension Scores */}
            <section className={styles["email-subject-tester__dimensions"]}>
              <h3>Performance Breakdown</h3>
              <div className={styles["email-subject-tester__dimension-grid"]}>
                {/* Length */}
                <div className={styles["email-subject-tester__dimension"]}>
                  <div className={styles["email-subject-tester__dimension-header"]}>
                    <span className={styles["email-subject-tester__dimension-name"]}>Length</span>
                    <span className={styles["email-subject-tester__dimension-score"]}>
                      {score.length.score}%
                    </span>
                  </div>
                  <div className={styles["email-subject-tester__progress-bar"]}>
                    <div
                      className={styles["email-subject-tester__progress-fill"]}
                      style={{
                        width: `${score.length.score}%`,
                        backgroundColor: getScoreColor(score.length.score),
                      }}
                    />
                  </div>
                  <p className={styles["email-subject-tester__dimension-message"]}>
                    {score.length.message}
                  </p>
                </div>

                {/* Urgency */}
                <div className={styles["email-subject-tester__dimension"]}>
                  <div className={styles["email-subject-tester__dimension-header"]}>
                    <span className={styles["email-subject-tester__dimension-name"]}>Urgency</span>
                    <span className={styles["email-subject-tester__dimension-score"]}>
                      {score.urgency.score}%
                    </span>
                  </div>
                  <div className={styles["email-subject-tester__progress-bar"]}>
                    <div
                      className={styles["email-subject-tester__progress-fill"]}
                      style={{
                        width: `${score.urgency.score}%`,
                        backgroundColor: getScoreColor(score.urgency.score),
                      }}
                    />
                  </div>
                  <p className={styles["email-subject-tester__dimension-message"]}>
                    {score.urgency.message}
                  </p>
                </div>

                {/* Personalization */}
                <div className={styles["email-subject-tester__dimension"]}>
                  <div className={styles["email-subject-tester__dimension-header"]}>
                    <span className={styles["email-subject-tester__dimension-name"]}>
                      Personalization
                    </span>
                    <span className={styles["email-subject-tester__dimension-score"]}>
                      {score.personalization.score}%
                    </span>
                  </div>
                  <div className={styles["email-subject-tester__progress-bar"]}>
                    <div
                      className={styles["email-subject-tester__progress-fill"]}
                      style={{
                        width: `${score.personalization.score}%`,
                        backgroundColor: getScoreColor(score.personalization.score),
                      }}
                    />
                  </div>
                  <p className={styles["email-subject-tester__dimension-message"]}>
                    {score.personalization.message}
                  </p>
                </div>

                {/* Curiosity */}
                <div className={styles["email-subject-tester__dimension"]}>
                  <div className={styles["email-subject-tester__dimension-header"]}>
                    <span className={styles["email-subject-tester__dimension-name"]}>Curiosity</span>
                    <span className={styles["email-subject-tester__dimension-score"]}>
                      {score.curiosity.score}%
                    </span>
                  </div>
                  <div className={styles["email-subject-tester__progress-bar"]}>
                    <div
                      className={styles["email-subject-tester__progress-fill"]}
                      style={{
                        width: `${score.curiosity.score}%`,
                        backgroundColor: getScoreColor(score.curiosity.score),
                      }}
                    />
                  </div>
                  <p className={styles["email-subject-tester__dimension-message"]}>
                    {score.curiosity.message}
                  </p>
                </div>

                {/* Power Words */}
                <div className={styles["email-subject-tester__dimension"]}>
                  <div className={styles["email-subject-tester__dimension-header"]}>
                    <span className={styles["email-subject-tester__dimension-name"]}>Power Words</span>
                    <span className={styles["email-subject-tester__dimension-score"]}>
                      {score.powerWords.score}%
                    </span>
                  </div>
                  <div className={styles["email-subject-tester__progress-bar"]}>
                    <div
                      className={styles["email-subject-tester__progress-fill"]}
                      style={{
                        width: `${score.powerWords.score}%`,
                        backgroundColor: getScoreColor(score.powerWords.score),
                      }}
                    />
                  </div>
                  <p className={styles["email-subject-tester__dimension-message"]}>
                    {score.powerWords.message}
                  </p>
                </div>

                {/* Special Characters */}
                <div className={styles["email-subject-tester__dimension"]}>
                  <div className={styles["email-subject-tester__dimension-header"]}>
                    <span className={styles["email-subject-tester__dimension-name"]}>Formatting</span>
                    <span className={styles["email-subject-tester__dimension-score"]}>
                      {score.specialCharacters.score}%
                    </span>
                  </div>
                  <div className={styles["email-subject-tester__progress-bar"]}>
                    <div
                      className={styles["email-subject-tester__progress-fill"]}
                      style={{
                        width: `${score.specialCharacters.score}%`,
                        backgroundColor: getScoreColor(score.specialCharacters.score),
                      }}
                    />
                  </div>
                  <p className={styles["email-subject-tester__dimension-message"]}>
                    {score.specialCharacters.message}
                  </p>
                </div>
              </div>
            </section>

            {/* Statistics */}
            <section className={styles["email-subject-tester__stats-section"]}>
              <h3>Statistics</h3>
              <div className={styles["email-subject-tester__stats-grid"]}>
                <div className={styles["email-subject-tester__stat"]}>
                  <div className={styles["email-subject-tester__stat-value"]}>{stats.wordCount}</div>
                  <div className={styles["email-subject-tester__stat-label"]}>Words</div>
                </div>
                <div className={styles["email-subject-tester__stat"]}>
                  <div className={styles["email-subject-tester__stat-value"]}>{stats.characterCount}</div>
                  <div className={styles["email-subject-tester__stat-label"]}>Characters</div>
                </div>
                <div className={styles["email-subject-tester__stat"]}>
                  <div className={styles["email-subject-tester__stat-value"]}>{stats.numbersCount}</div>
                  <div className={styles["email-subject-tester__stat-label"]}>Numbers</div>
                </div>
                <div className={styles["email-subject-tester__stat"]}>
                  <div className={styles["email-subject-tester__stat-value"]}>
                    {stats.hasEmoji ? "✓" : "-"}
                  </div>
                  <div className={styles["email-subject-tester__stat-label"]}>Emoji</div>
                </div>
              </div>
            </section>

            {/* Suggestions */}
            <section className={styles["email-subject-tester__suggestions"]}>
              <h3>Recommendations</h3>
              <ul className={styles["email-subject-tester__suggestion-list"]}>
                {score.suggestions.map((suggestion, idx) => (
                  <li key={idx} className={styles["email-subject-tester__suggestion-item"]}>
                    {suggestion}
                  </li>
                ))}
              </ul>
            </section>

            {/* Actions */}
            <div className={styles["email-subject-tester__actions"]}>
              <button
                className={styles["email-subject-tester__button"]}
                onClick={handleCopyScore}
              >
                📋 Copy Score
              </button>
              <button
                className={styles["email-subject-tester__button"]}
                onClick={handleDownloadReport}
              >
                ⬇️ Download Report
              </button>
            </div>

            {copyMessage && (
              <div className={styles["email-subject-tester__copy-message"]}>
                {copyMessage}
              </div>
            )}
          </>
        )}
      </main>

      <footer className={styles["email-subject-tester__footer"]}>
        <p>
          <small>
            Free tool by{" "}
            <a href="/" className={styles["email-subject-tester__link"]}>
              topaitoolrank.com
            </a>
          </small>
        </p>
      </footer>
    </div>
  );
}

