import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Top AI Tool Rank",
  description:
    "Read our privacy policy to learn how Top AI Tool Rank collects, uses, and protects your personal data.",
  alternates: {
    canonical: "https://topaitoolrank.com/privacy-policy",
  },
  openGraph: {
    title: "Privacy Policy - Top AI Tool Rank",
    description:
      "Read our privacy policy to learn how Top AI Tool Rank protects your personal data.",
    url: "https://topaitoolrank.com/privacy-policy",
  },
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <nav className="navbar">
        <div className="container nav-container">
          <div className="logo">
            <a href="/">Top AI Tool Rank</a>
          </div>
          <ul className="nav-menu">
            <li>
              <a href="/#home" className="nav-link">
                Home
              </a>
            </li>
            <li>
              <a href="/#services" className="nav-link">
                Services
              </a>
            </li>
            <li className="nav-item-dropdown">
              <a href="/#tools" className="nav-link">
                Tools
              </a>
              <ul className="dropdown">
                <li>
                  <a href="/tools/wa-sender" rel="noopener">
                    WA Sender
                  </a>
                </li>
                <li>
                  <a href="#coming-soon" className="coming-soon">
                    Voice Rating (Coming Soon)
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <a href="/blogs/" className="nav-link">
                Blogs
              </a>
            </li>
            <li>
              <a href="/#contact" className="nav-link">
                Contact
              </a>
            </li>
          </ul>
          <div className="hamburger">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
      </nav>

      <main className="legal-content">
        <h1>Privacy Policy</h1>
        <p className="last-updated">Last updated: January 2024</p>

        <h2>1. Introduction</h2>
        <p>
          Top AI Tool Rank ("we," "our," or "us") is committed to protecting
          your privacy. This Privacy Policy explains how we collect, use,
          disclose, and safeguard your information when you visit our website,
          including any other media form, media channel, mobile website, or
          mobile application related to, operated, or connected thereto
          (collectively, the "Site").
        </p>

        <h2>2. Information We Collect</h2>
        <p>We collect information in the following ways:</p>
        <ul>
          <li>
            <strong>Contact Form Information:</strong> When you submit the
            contact form, we collect your name, email address, and message
            content.
          </li>
          <li>
            <strong>Analytics Data:</strong> We use Google Analytics 4 to
            understand how visitors use our site. This includes data about
            pages visited, time spent on pages, and your general location.
          </li>
          <li>
            <strong>Technical Information:</strong> We automatically collect
            information about your device, including browser type, IP address,
            and pages visited.
          </li>
        </ul>

        <h2>3. How We Use Your Information</h2>
        <p>We use the information we collect for the following purposes:</p>
        <ul>
          <li>To respond to your inquiries and provide customer service</li>
          <li>To improve our website and services</li>
          <li>To understand how our site is being used</li>
          <li>To comply with legal obligations</li>
          <li>To send you updates about our services (if you opt-in)</li>
        </ul>

        <h2>4. Google Analytics</h2>
        <p>
          We use Google Analytics to analyze how users interact with our
          website. Google Analytics uses cookies to collect information about
          your use of our website. The information generated by the cookie
          about your use of the website will be transmitted to Google and
          stored by Google. Google will use this information for the purpose of
          evaluating your use of the website and compiling reports on website
          activity.
        </p>

        <p>
          You can opt out of Google Analytics by installing the{" "}
          <a
            href="https://tools.google.com/dlpage/gaoptout"
            target="_blank"
            rel="noopener"
          >
            Google Analytics opt-out browser add-on
          </a>
          .
        </p>

        <h2>5. Data Security</h2>
        <p>
          We implement appropriate technical and organizational measures to
          protect your personal information against unauthorized access,
          alteration, disclosure, or destruction. However, no method of
          transmission over the internet is 100% secure, and we cannot
          guarantee absolute security.
        </p>

        <h2>6. Third-Party Services</h2>
        <p>
          Our website may contain links to third-party websites and services.
          This Privacy Policy does not apply to third-party services, and we
          are not responsible for their privacy practices. We encourage you to
          read the privacy policies of any third-party services before
          providing your information.
        </p>

        <h2>7. Your Rights</h2>
        <p>Depending on your location, you may have the right to:</p>
        <ul>
          <li>Access your personal data</li>
          <li>Correct inaccurate data</li>
          <li>Request deletion of your data</li>
          <li>Opt-out of marketing communications</li>
        </ul>

        <h2>8. Children's Privacy</h2>
        <p>
          Our website is not intended for children under the age of 13. We do
          not knowingly collect personal information from children under 13. If
          we become aware that we have collected information from a child under
          13, we will take steps to delete such information promptly.
        </p>

        <h2>9. Changes to This Privacy Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will notify
          you of any changes by updating the "Last updated" date of this
          Privacy Policy. Your continued use of the Site constitutes your
          acceptance of the updated Privacy Policy.
        </p>

        <h2>10. Contact Us</h2>
        <p>
          If you have questions about this Privacy Policy or our privacy
          practices, please contact us at:
        </p>
        <p>
          Email:{" "}
          <a href="mailto:contact@topaitoolrank.com">
            contact@topaitoolrank.com
          </a>
          <br />
          Website:{" "}
          <a href="https://topaitoolrank.com">topaitoolrank.com</a>
        </p>
      </main>

      <footer className="footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-section">
              <h4>Top AI Tool Rank</h4>
              <p>
                Building custom software solutions for businesses worldwide.
              </p>
            </div>
            <div className="footer-section">
              <h4>Quick Links</h4>
              <ul>
                <li>
                  <a href="/">Home</a>
                </li>
                <li>
                  <a href="/#services">Services</a>
                </li>
                <li>
                  <a href="/#tools">Tools</a>
                </li>
                <li>
                  <a href="/blogs/">Blogs</a>
                </li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Legal</h4>
              <ul>
                <li>
                  <a href="/privacy-policy">Privacy Policy</a>
                </li>
                <li>
                  <a href="/terms">Terms of Service</a>
                </li>
              </ul>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; 2026 Top AI Tool Rank. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </>
  );
}
